apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ryu-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ryu
  template:
    metadata:
      labels:
        app: ryu
    spec:
      containers:
      - name: ryu
        image: osrg/ryu
        command: ["ryu-manager"]
        args: ["--verbose", "ryu.app.simple_switch_13"]
        ports:
        - containerPort: 6653
